### ISSUE TITLE
Host this project on hex.pm

### ISSUE THREAD

**Issue by whitfin** [k1complete/qlc#1]
It'd be nice if this were on https://hex.pm/.

As it stands, you have to manually include this in your project.

**Comment by whitfin** [comment]
I have filed a PR with some neatening up and some more metadata in the `mix.exs` file, in hopes that they make it into the repo and this project can go to `1.0.0` on Hex.pm.

PR: https://github.com/k1complete/qlc/pull/2

**Comment by k1complete** [comment]
I have published qlc to hex.pm! very thanks!!
