### ISSUE TITLE
Compilation error in file lib/qlc.ex elixir 1.10.1, Erlang/OTP 22

### ISSUE THREAD

**Issue by anuragjain67** [k1complete/qlc#10]
== Compilation error in file lib/qlc.ex ==
** (RuntimeError) error parsing file /usr/local/lib/erlang/lib/stdlib-3.11.2/src/qlc.erl, got: {:error, :enoent}
    (elixir 1.10.1) lib/record/extractor.ex:84: Record.Extractor.read_file/2
    (elixir 1.10.1) lib/record/extractor.ex:50: Record.Extractor.extract_record/2
    lib/qlc.ex:134: (module)
    (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :qlc, "mix compile" failed. You can recompile this dependency with "mix deps.compile qlc", update it with "mix deps.update qlc" or clean it with "mix deps.clean qlc"

**Comment by k1complete** [comment]
Hi, 
I think, that it occurred build environment(cache) version mismatch.
Please try to solving, In project top level :
```sh
  % mix deps.clean qlc
  % mix deps.update qlc
  % mix deps.compile qlc
```
>(RuntimeError) error parsing file /usr/local/lib/erlang/lib/stdlib-3.11.2/src/qlc.erl, got: {:error, :enoent}

 your build system is maybe OTP22.2.5 or higher, but not (OTP22.0 is stdlib-3.9)

**Comment by anuragjain67** [comment]
I have tried  but didn't work
  % mix deps.clean qlc
  % mix deps.update qlc
  % mix deps.compile qlc



yes you are right Erl version is 22.2.8, what will be the fix for the same?

**Comment by k1complete** [comment]
Thanks! 
Fixed this problem and tagged 1.0.8.
OTP "source" distribution required, but it wad bad.

**Comment by anuragjain67** [comment]
Thank you so much, when will it be available here - https://hex.pm/packages/qlc/versions ?

**Comment by k1complete** [comment]
Sorry! I forgot publish it! I have done it now.
see again http://hex.pm/packages/qlc/1.0.8 !
