### ISSUE TITLE
README example error

### ISSUE THREAD

**Issue by haroldvera** [k1complete/qlc#12]
Your README example response,

== Compilation error in file lib/node_data.ex ==
** (UndefinedFunctionError) function Record.__fields__/2 is undefined or private
    (elixir 1.13.4) Record.__fields__(:test, [id: nil, unique_id: nil, creator: nil])
    (stdlib 3.17.2) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17.2) erl_eval.erl:446: :erl_eval.expr/5
    (stdlib 3.17.2) erl_eval.erl:123: :erl_eval.exprs/5
    expanding macro: Test.test!/2
    lib/node_data.ex:55: Test.query/0
    (elixir 1.13.4) expanding macro: Kernel.to_string/1
    lib/node_data.ex:55: Test.query/0

**Comment by k1complete** [comment]
Hello!
Thank you for your report.
In Elixir, the [Add reflection of records] (https://github.com/elixir-lang/elixir/commit/f32a4a3f22629518e850a01067226cbe7c04c2b4) patch has removed \_\_fields\_\_ /2.
I'm going to change the implementation of Qlc.Record.defrecord/2.
