### ISSUE TITLE
Key Sort in QLC

### ISSUE THREAD

**Issue by nitinjain1105** [k1complete/qlc#5]
Hi @k1complete 

Do you have any function to sort (or keysort) the result obtained by Qlc.q/2 ?

I couldn't find anything in Qlc module. Please help.

**Comment by k1complete** [comment]
Oh! sorry. I have mistake. Now, Qlc module dose not provide sort/2, keysort/3 and anything.
You may  use erlang qlc module  at workarround :
  Qlc.q("query", binding) |> :qlc.sort() |> Qlc.e()
I will add sort/2, keysort/3 and more to Qlc module.
Please wait.

**Comment by k1complete** [comment]
I released v1.0.4. 
sort/2, keysort/3 and table/2 added.
please read [https://hexdocs.pm/qlc/Qlc.html#keysort/3](url).

**Comment by nitinjain1105** [comment]
Thank you @k1complete
