### ISSUE TITLE
How to use records with mnesia?

### ISSUE THREAD

**Issue by UA3MQJ** [k1complete/qlc#6]
subj

**Comment by k1complete** [comment]
Hi, You may use :mnesia.table/1 with mnesia database.
:mnesia.table/1 will return qlc_handle to passing to Qlc.q/2.
See, [mnesia manual](http://erlang.org/doc/man/mnesia.html#table-1)

**Comment by UA3MQJ** [comment]
Thanks!
I wanted to know how to do this, if possible. As example
```
qlc_handle =  Qlc.q("[P#citys.name || P <- ets:table(citys), P#citys.id == 10]", []) 
```
And i received an error because the record is unknown.
I needed access to individual fields. But i can use the element/2 function.
```
qlc_handle =  Qlc.q("[ element(2, P) || P <- ets:table(citys), element(1, P) == 10]", []) 
```
