### ISSUE TITLE
`:qlc.next_answers` implementation

### ISSUE THREAD

**Issue by patatoid** [k1complete/qlc#9]
First thanks for the package that is really helpful for my project :)

I am looking forward using qlc `next_answers` function. For now I do
```
      cursor = Qlc.cursor(query)
      :qlc.next_answers(cursor.c, limit)
      |> :qlc.e()
```
which works fine but bypass the elixir implementation.

It would be great to have that function !

**Comment by k1complete** [comment]
Hi, thanks to great your proposal.
I think that I should add  Qlc.next_answers/2 to Qlc.
I tagged v1.0.7  added Qlc.next_anserws/2.
Please check it.
Regards.
